version: "3"

tasks:
  help:
    desc: print this help message
    cmds:
      - task --list-all
    silent: true

  build:
    desc: build the project
    cmds:
      - cd database && go build -o database-service ./cmd/database
      - cd engine && go build -o engine-service ./cmd/engine
      - cd server && go build -o server-service ./cmd/server
      - cd socket && go build -o socket-service ./cmd/socket

  run:
    desc: run all applications
    cmds:
      - cd database && go run ./cmd/database/main.go &
      - cd engine && go run ./cmd/engine/main.go &
      - cd server && go run ./cmd/server/main.go &
      - cd socket && go run ./cmd/socket/main.go &

  dev:
    desc: run all applications with live reload
    deps: [database, engine, server, socket]
    run: once
    parallel: true

  database:
    cmds:
      - cd database && air -c .air.toml

  engine:
    cmds:
      - cd engine && air -c .air.toml

  server:
    cmds:
      - cd server && air -c .air.toml

  socket:
    cmds:
      - cd socket && air -c .air.toml
